name: 'template name'
description: 'template description'
author: 'MeilCli'
branding:
  icon: package
  color: gray-dark
inputs:
  github_token:
    description: 'github token, using to read repository'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
